# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profiling.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprofiling.proto\x12\x06vaccel\x1a\x0b\x65rror.proto\"&\n\x10ProfilingRequest\x12\x12\n\nsession_id\x18\x01 \x01(\r\"m\n\nProfRegion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x07samples\x18\x02 \x03(\x0b\x32\x19.vaccel.ProfRegion.Sample\x1a%\n\x06Sample\x12\r\n\x05start\x18\x01 \x01(\x04\x12\x0c\n\x04time\x18\x02 \x01(\x04\"0\n\x0bProfRegions\x12!\n\x05timer\x18\x01 \x03(\x0b\x32\x12.vaccel.ProfRegion\"8\n\x11ProfilingResponse\x12#\n\x06result\x18\x01 \x01(\x0b\x32\x13.vaccel.ProfRegionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profiling_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROFILINGREQUEST']._serialized_start=40
  _globals['_PROFILINGREQUEST']._serialized_end=78
  _globals['_PROFREGION']._serialized_start=80
  _globals['_PROFREGION']._serialized_end=189
  _globals['_PROFREGION_SAMPLE']._serialized_start=152
  _globals['_PROFREGION_SAMPLE']._serialized_end=189
  _globals['_PROFREGIONS']._serialized_start=191
  _globals['_PROFREGIONS']._serialized_end=239
  _globals['_PROFILINGRESPONSE']._serialized_start=241
  _globals['_PROFILINGRESPONSE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
