# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x12\x06vaccel\"%\n\x14\x43reateSessionRequest\x12\r\n\x05\x66lags\x18\x01 \x01(\r\"9\n\x14UpdateSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\r\"+\n\x15\x44\x65stroySessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\r\"+\n\x15\x43reateSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATESESSIONREQUEST']._serialized_start=25
  _globals['_CREATESESSIONREQUEST']._serialized_end=62
  _globals['_UPDATESESSIONREQUEST']._serialized_start=64
  _globals['_UPDATESESSIONREQUEST']._serialized_end=121
  _globals['_DESTROYSESSIONREQUEST']._serialized_start=123
  _globals['_DESTROYSESSIONREQUEST']._serialized_end=166
  _globals['_CREATESESSIONRESPONSE']._serialized_start=168
  _globals['_CREATESESSIONRESPONSE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
