# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: torch.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btorch.proto\x12\x06vaccel\x1a\x0b\x65rror.proto\"N\n\x0bTorchTensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64ims\x18\x02 \x03(\r\x12#\n\x04type\x18\x03 \x01(\x0e\x32\x15.vaccel.TorchDataType\"\x80\x01\n\x1aTorchJitloadForwardRequest\x12\x12\n\nsession_id\x18\x01 \x01(\r\x12\x10\n\x08model_id\x18\x02 \x01(\x03\x12\x13\n\x0brun_options\x18\x03 \x01(\x0c\x12\'\n\nin_tensors\x18\x04 \x03(\x0b\x32\x13.vaccel.TorchTensor\"E\n\x19TorchJitloadForwardResult\x12(\n\x0bout_tensors\x18\x01 \x03(\x0b\x32\x13.vaccel.TorchTensor\"\x88\x01\n\x1bTorchJitloadForwardResponse\x12$\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x13.vaccel.VaccelErrorH\x00\x12\x39\n\x0ctorch_result\x18\x02 \x01(\x0b\x32!.vaccel.TorchJitloadForwardResultH\x00\x42\x08\n\x06result*l\n\rTorchDataType\x12\x10\n\x0cTORCH_UNUSED\x10\x00\x12\t\n\x05UInt8\x10\x01\x12\x08\n\x04Int8\x10\x02\x12\t\n\x05Int16\x10\x03\x12\t\n\x05Int32\x10\x04\x12\t\n\x05Int64\x10\x05\x12\x08\n\x04Half\x10\x06\x12\t\n\x05\x66loat\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'torch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TORCHDATATYPE']._serialized_start=457
  _globals['_TORCHDATATYPE']._serialized_end=565
  _globals['_TORCHTENSOR']._serialized_start=36
  _globals['_TORCHTENSOR']._serialized_end=114
  _globals['_TORCHJITLOADFORWARDREQUEST']._serialized_start=117
  _globals['_TORCHJITLOADFORWARDREQUEST']._serialized_end=245
  _globals['_TORCHJITLOADFORWARDRESULT']._serialized_start=247
  _globals['_TORCHJITLOADFORWARDRESULT']._serialized_end=316
  _globals['_TORCHJITLOADFORWARDRESPONSE']._serialized_start=319
  _globals['_TORCHJITLOADFORWARDRESPONSE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
